version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - export AWS_REGION=us-east-1
      - npm install

  build:
    commands:
      - npm test
      - npm audit
      - jest

artifacts:
  files:
    - "**/*"
