version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - export AWS_REGION=us-east-1 # Reemplaza 'your_region' con la región de AWS que estés utilizando
      - npm install

  build:
    commands:
      - npm test ./tests/lettercounte.js
      - npm audit fix
      - npm jest

artifacts:
  files:
    - "**/*"
